# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "ferrobean"
main = "build/index.js"
compatibility_date = "2025-09-20"

[build]
command = "cargo install -q worker-build && worker-build --release"