name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run cargo check
      run: |
        cargo check --verbose
        echo "cargo check completed with exit code: $?"
    - name: Run cargo test
      run: |
        cargo test --verbose
        echo "cargo test completed with exit code: $?"